### PR TITLE
1152: Toast placement for copy, create, delete

### LINKED ISSUE #1152: The deletion confirmation snackbar is displayed over the + button
## Steps to reproduce
1. Launch lockwise.
2. Login with valid credentials.
3. Select an account and delete it.
### Expected behavior
The deletion confirmation snackbar is displayed under the `+` button.
### Actual behavior
The deletion confirmation snackbar is displayed over the `+` button.
### Device & build information
* Device: Samsung Galaxy S10+(Android 9)
* Build version: 4.0.0(6016)
### Notes
Attachments: 
Screenshot_20200129-163734

### PR DESCRIPTION
**Pull request by eliserichards**
Fixes #1152 

Specify each bottom margin for the toast notifications. The `bottomMargin` value set based on the nav location: toasts on the item list will appear above the `+` create button, and other toasts will have the normal bottom margin at the bottom of the screen.

## Testing and Review Notes
* copy username/copy password appear at the bottom of the screen
* delete confirmation appears above the `+` button on the item list
* create confirmation appears on the item detail screen at the bottom (same place as copy)

## Screenshots or Videos
_(save gif tbd on #1163)_

copy_toasts

delete_toast

## To Do

- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockwise.github.io/lockwise-android/accessibility/) of any added UI

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/model/ToastNotificationViewModel.kt [hunk 1]
```diff
@@ -12,5 +12,6 @@ import androidx.annotation.StringRes
 data class ToastNotificationViewModel(
     @StringRes val message: Int,
     @DrawableRes val icon: Int,
-    val messageParam: String? = null
+    val messageParam: String? = null,
+    val bottomMargin: Int
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/model/ToastNotificationViewModel.kt]: This is the model, rather than the UI for that model.

File: app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt [hunk 2]
```diff
@@ -122,7 +122,7 @@ abstract class RoutePresenter(
         val layoutInflater = LayoutInflater.from(activity)
 
         toast.view = layoutInflater.inflate(R.layout.toast_view, container, false)
-        toast.setGravity(Gravity.FILL_HORIZONTAL or Gravity.BOTTOM, 0, 216)
+        toast.setGravity(Gravity.FILL_HORIZONTAL or Gravity.BOTTOM, 0, action.viewModel.bottomMargin)
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt]: I don't think this is the correct approach. The position of the toast is a function of the screen that it's on, rather than the actual toast that needs to be displayed.

The margin needs to be chosen in the `RoutePresenter`.

There are two other approaches I can think of: 

1. Easy: choose the bottom margin  based on whether or not the current destination is the `ItemList`.
2. Harder: allow the bottom margin to be determined from something in the layout of the current fragment or activity.

File: app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt [hunk 3]
```diff
@@ -122,7 +122,18 @@ abstract class RoutePresenter(
         val layoutInflater = LayoutInflater.from(activity)
 
         toast.view = layoutInflater.inflate(R.layout.toast_view, container, false)
-        toast.setGravity(Gravity.FILL_HORIZONTAL or Gravity.BOTTOM, 0, 216)
+
+        val bottomMargin = if (action is ToastNotificationAction.ShowDeleteToast) {
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt]: > Easy: choose the bottom margin based on whether or not the current destination is the ItemList.

```kotlin
val bottomMargin = if (navController.currentDestination?.id == R.id.fragment_item_list) {
```

File: app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt [hunk 4]
```diff
@@ -122,7 +122,18 @@ abstract class RoutePresenter(
...
+            R.dimen.toast_bottom_margin_large
+        } else {
+            R.dimen.toast_bottom_margin_small
+        }
+
+        toast.setGravity(
+            Gravity.FILL_HORIZONTAL or Gravity.BOTTOM,
+            0,
+            activity.resources.getDimension(bottomMargin).toInt()
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt]: This is good.

File: app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt (hunk 3 above)
Comment (jhugman) [reply app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt]: This way we can make all toasts that are displayed on the Item List avoid the `+` button, not just the delete one.

Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/presenter/RoutePresenter.kt]: Oh that makes perfect sense. Done.
