### PR TITLE
791: Remove fake timeout from sync

### LINKED ISSUE #791: Remove Sync timeout
## Steps to reproduce
1. Open Lockwise and login with a Mozilla account that has saved logins.
2. Drag down from the top of the screen in order to trigger the sync.

### Expected behavior
The saved logins from the Mozilla account should be displayed.

### Actual behavior
The "Syncing has timed out error" is displayed and the logins are not retrieved.

### Device & build information
* Device: Samsung Galaxy S9 (Android 8.0.0)
* Build version: Lockwise version 1.1.2 (Build 4342)

### Notes
The issue only occurs when using the account laursv52@mailinator.com pass: softvision
Attachments: 
Syncing has timed out error is displayed constantly
[logcat.txt](https://github.com/mozilla-lockwise/lockwise-android/files/3330073/logcat.txt)

### Eng todo
- [ ] add telemetry around timeout

### PR DESCRIPTION
**Pull request by eliserichards**
Fixes #791

## Testing and Review Notes
The toast notification was removed in #833, but the actual logic was still present. This PR removes all of that (if we want a timeout, it should be implemented on the sync side and then handled by us).

## To Do

- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] remove ~add~ unit tests
- [ ] ~request the "UX" team perform a design review (if/when applicable)~
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)

### CODE REVIEW

**Comment by eliserichards** [comment]
Rebased with new strings from #881. Removed all of the sync timeout strings in here. We'll have to force sync with Pontoon, I'm guessing? @Delphine

File: app/src/main/java/mozilla/lockbox/store/DataStore.kt [hunk 1]
```diff
@@ -261,21 +253,15 @@ open class DataStore(
...
             }
-            .timeout(Constant.App.syncTimeout, TimeUnit.SECONDS)
-            .doOnEvent { _, err ->
-                (err as? TimeoutException).let {
-                    // syncStateSubject.accept(SyncState.TimedOut)
-                    dispatcher.dispatch(DataStoreAction.SyncTimeout(it?.message ?: ""))
-                }.run {
-                    syncStateSubject.accept(SyncState.NotSyncing)
-                }
+            .doOnEvent { _, _ ->
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/store/DataStore.kt]: Can we remove 

```kotlin
            .map {
                log.debug("Hashed UID: $it")
            }
```

too?

Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/store/DataStore.kt]: That's going to be handled in #870 (next up in the sprint backlog! 🎸)

**Comment by Delphine** [comment]
> Rebased with new strings from #881. Removed all of the sync timeout strings in here. We'll have to force sync with Pontoon, I'm guessing? @Delphine

Yes! I'll ping Matjaz now (he's in Europe so not sure he's still around at this time)
