### PR TITLE
981: Ensure that menu options aren't replayed in detail popup menu.

### LINKED ISSUE #981: Empty Edit view is shown if tapping the system back button while in Edit Mode
## Steps to reproduce
1. Launch Lockwise.
2. Login with valid credentials.
3. Access any account.
4. Tap on 3 dot menu and enter the Edit Login mode.
5. Tap back(on the device button or Lockwise button).

### Expected behavior
The discard changes dialog is shown to the user.

### Actual behavior
Every field is cleared with a message below that Password cannot be empty.
image

### Device & build information
* Device: Google Pixel 3a XL(Android 9)
* Build version: Latest build from master(17/10/2019)

### Notes
Attachments: 
[Video](https://drive.google.com/file/d/1OdaFCWBVZCFzjI1Q2CSVNcQGTRpyHEnm/view?usp=sharing)

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #981

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/view/ItemDetailFragment.kt [hunk 1]
```diff
@@ -87,8 +87,8 @@ class ItemDetailFragment : BackableFragment(), ItemDetailView {
     override val kebabMenuClicks: Observable<Unit>
         get() = view!!.toolbar.kebabMenuButton.clicks()
 
-    override val editClicks: BehaviorRelay<Unit> = BehaviorRelay.create()
-    override val deleteClicks: BehaviorRelay<Unit> = BehaviorRelay.create()
+    override val editClicks: Observable<Unit> = PublishSubject.create()
```
Comment (eliserichards) [inline app/src/main/java/mozilla/lockbox/view/ItemDetailFragment.kt]: `PublishSubject` instead of `BehaviorRelay` 🤦‍♀
