### PR TITLE
904: Delete from edit view shows confirmation dialog

### LINKED ISSUE #904: Edit View: There is no disclaimer menu when tapping on Delete Entry from Edit View
## Steps to reproduce
Open one entry
Tap on hamburger menu -> Edit
Tap on Delete Entry
### Expected behavior
I would expect a disclaimer in case I regret removing the entry
### Actual behavior
There is no disclaimer to confirm the deletion, upon clicking on Delete entry, that's removed
### Device & build information
* Device: Pixel 3, API 28
* Build version: latest master b07e161

### PR DESCRIPTION
**Pull request by eliserichards**
Fixes #904

## To Do

- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockwise.github.io/lockwise-android/accessibility/) of any added UI

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt [hunk 1]
```diff
@@ -138,17 +133,18 @@ class EditItemPresenter(
...
+                httpRealm = cred.httpRealm,
+                formSubmitURL = cred.formSubmitURL
             )
-        } catch (exception: NullPointerException) {
-            pushError(exception, "Error editing credential with id ${credentials?.id}")
-        }
+        } ?: pushError(
+            NullPointerException("Credentials are null"),
+            "Error editing credential with id ${credentials?.id}"
+        )
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt]: :sparkles: This code is much much better; not least because this works as intended. :sparkles:

File: app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt [hunk 2]
```diff
@@ -81,15 +81,12 @@ class EditItemPresenter(
 
         view.deleteClicks
             .subscribe {
-                if (credentials != null) {
-                    dispatcher.dispatch(DataStoreAction.Delete(credentials!!))
-                    dispatcher.dispatch(RouteAction.ItemList)
-                } else {
-                    pushError(
+                credentials?.let { c ->
+                    dispatcher.dispatch(DialogAction.DeleteConfirmationDialog(c))
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt]: Nit: For such a small use of `c` I think I would advocate for using the anonymous `it` name.

Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt]: Will fix this in #603 :)

File: app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt (hunk 1 above)
Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt]: 🚀
