### PR TITLE
603: Error states and text validation for edit view

### LINKED ISSUE #603: Error states and field validation for edit
When I go to edit an existing credential, I want to know when I’ve either missed a required field or entered incorrect data. I don’t want to save information that isn’t useful to me when I next go to log into that account.

## Requirements
* Should detect and then serve an error message when nothing OR an invalid URL is entered into the web address
* Should detect and then serve an error message [Password cannot be empty] when nothing is entered into the password field
* Error messages should provide helpful guidance for correcting the data

## Visual Design

Zeplin: https://app.zeplin.io/project/5b6895bfe4af825140aa8dbc/screen/5c548fc49c3e07307b35a574
Invision: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/screens/344499813

Screen Shot 2019-07-11 at 9 26 13 AM

### PR DESCRIPTION
**Pull request by eliserichards**
Fixes #603 

### Engineering tasks

- [x] hide keyboard when clicking out of the edittext
- [x] show password when focused
- [x] change warning icon
- [x] change text color on warning
- [x] show warning text
- [x] warning should replace the helper text
- [x] when username is empty, make sure the name of the field stays above

### Other

- [x] add “WIP” to the PR title if pushing up but not complete nor ready for review
- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockwise.github.io/lockwise-android/accessibility/) of any added UI

### CODE REVIEW

File: app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt [hunk 1]
```diff
@@ -49,6 +58,130 @@ class EditItemFragment : BackableFragment(), EditItemDetailView {
...
+            ) {
+            }
+
+            override fun onTextChanged(
+                charSequence: CharSequence,
+                start: Int,
+                before: Int,
+                count: Int
+            ) {
+            }
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: Nit: empty blocks should have a comment saying their empty. 

e.g. 

```kotlin
{
    // NOOP
}

```

File: app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt [hunk 2]
```diff
@@ -49,6 +58,130 @@ class EditItemFragment : BackableFragment(), EditItemDetailView {
...
+            override fun afterTextChanged(editable: Editable) {
+                val inputText: String? = errorLayout.editText?.text.toString()
+
+                when (errorLayout.id) {
+                    R.id.inputLayoutHostname -> {
+                        // hostname cannot be null
+                        // has to have http:// or https://
+                        when {
+                            TextUtils.isEmpty(inputText)
+                                || (!URLUtil.isHttpUrl(inputText) and !URLUtil.isHttpsUrl(inputText))
```
Comment (mnoorenberghe) [inline app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: We don't have such a restriction in any of the Firefox browsers so I don't see why we should have that in Lockwise. The origin field is a URI, not a URL e.g. `ftp://example.com`, `file:///`, and `chrome://FirefoxAccounts` are all values that we currently store and Sync.

File: app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt [hunk 3]
```diff
@@ -49,6 +58,130 @@ class EditItemFragment : BackableFragment(), EditItemDetailView {
...
+            ) {
+            }
+
+            override fun afterTextChanged(editable: Editable) {
+                val inputText: String? = errorLayout.editText?.text.toString()
+
+                when (errorLayout.id) {
+                    R.id.inputLayoutHostname -> {
+                        // hostname cannot be null
+                        // has to have http:// or https://
```
Comment (mnoorenberghe) [inline app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: You should also ensure that there are no path segments i.e. https://www.example.com is valid whereas https://www.example.com/ and https://www.example.com/foo are invalid.

Comment (mnoorenberghe) [reply app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: We decided not to allow editing of this field on desktop for now because users can make changes to it which break autofill so you could also de-prioritize editing of the origin and only allow editing this field for new logins though my comments here about not including path segments or limiting the scheme still applies.

File: app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt [hunk 4]
```diff
@@ -49,6 +58,130 @@ class EditItemFragment : BackableFragment(), EditItemDetailView {
...
+            if (!hasFocus) {
+                closeKeyboard()
+            }
+        }
+
+        view.inputUsername.onFocusChangeListener = View.OnFocusChangeListener { _, hasFocus ->
+            if (!hasFocus) {
+                closeKeyboard()
+            }
+        }
```
[the remark this answers is not in the document]
Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: Nice, I didn't realize that you could use the same `listener` for multiple items

File: app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt [hunk 5]
```diff
@@ -49,6 +58,130 @@ class EditItemFragment : BackableFragment(), EditItemDetailView {
...
+        view.inputUsername.addTextChangedListener(
+            buildTextWatcher(
+                view.inputLayoutUsername
+            )
+        )
+        view.inputPassword.addTextChangedListener(
+            buildTextWatcher(
+                view.inputLayoutPassword
+            )
+        )
```
[the remark this answers is not in the document]
Comment (eliserichards) [reply app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: yes indeed!

File: app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt [hunk 6]
```diff
@@ -116,8 +124,8 @@ class EditItemPresenter(
 
         view.saveEntryClicks
             .subscribe {
-                credentials?.let { c ->
-                    dispatcher.dispatch(DataStoreAction.UpdateItemDetail(c))
+                credentials?.let {
+                    dispatcher.dispatch(DataStoreAction.UpdateItemDetail(it))
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/presenter/EditItemPresenter.kt]: 😻

File: app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt [hunk 7]
```diff
@@ -49,48 +82,152 @@ class EditItemFragment : BackableFragment(), EditItemDetailView {
     override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
         super.onViewCreated(view, savedInstanceState)
         setupToolbar(view.toolbar)
-    }
+        setTextWatcher(view)
+        setKeyboardFocus(view)
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: Nit: use `setupX(view)` instead of `setX(view)`. 

If you're setting X, this would be analagous to `this.X = view`, which is not what you're doing.

File: app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt [hunk 8]
```diff
@@ -49,48 +82,152 @@ class EditItemFragment : BackableFragment(), EditItemDetailView {
...
+                    }
+                    R.id.inputLayoutUsername -> {
+                        handleUsernameChanges(errorLayout, inputText)
+                    }
+                    R.id.inputLayoutPassword -> {
+                        handlePasswordChanges(errorLayout, inputText)
+                    }
+                    else -> {
+                        errorLayout.error = null
+                    }
```
Comment (jhugman) [inline app/src/main/java/mozilla/lockbox/view/EditItemFragment.kt]: Unnit: This is the case I was talking about: using `switch`/`when` especially in multiple places is an indicator that you should be using a State pattern, so a class for each state. In this case, this would map to a `TextWatcher` class per input.

The trade offs for this aren't obvious, especially on constrained devices with low method count limits.
